// https://nuxt.com/docs/api/configuration/nuxt-config
// CPEK - Nuxt 3 (Nitro). Desktop-first financial app.
import Aura from '@primeuix/themes/aura'

export default defineNuxtConfig({
  compatibilityDate: '2024-11-01',
  devtools: { enabled: true },
  pages: true,

  modules: ['@pinia/nuxt', '@primevue/nuxt-module', '@nuxtjs/tailwindcss'],

  css: ['~/assets/css/main.css'],

  primevue: {
    options: {
      theme: {
        preset: Aura,
        options: {
          darkModeSelector: '.app-dark',
        },
      },
      locale: {
        startsWith: 'Começa com',
        contains: 'Contém',
        notContains: 'Não contém',
        endsWith: 'Termina com',
        equals: 'Igual a',
        notEquals: 'Diferente de',
        noFilter: 'Sem filtro',
        lt: 'Menor que',
        lte: 'Menor ou igual a',
        gt: 'Maior que',
        gte: 'Maior ou igual a',
        dateIs: 'Data é',
        dateIsNot: 'Data não é',
        dateBefore: 'Data é anterior a',
        dateAfter: 'Data é posterior a',
        clear: 'Limpar',
        apply: 'Aplicar',
        matchAll: 'Corresponder a todos',
        matchAny: 'Corresponder a qualquer',
        addRule: 'Adicionar regra',
        removeRule: 'Remover regra',
        accept: 'Sim',
        reject: 'Não',
        choose: 'Escolher',
        upload: 'Enviar',
        cancel: 'Cancelar',
        completed: 'Concluído',
        pending: 'Pendente',
        fileSizeTypes: ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'],
        dayNames: ['Domingo', 'Segunda-feira', 'Terça-feira', 'Quarta-feira', 'Quinta-feira', 'Sexta-feira', 'Sábado'],
        dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
        dayNamesMin: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],
        monthNames: [
          'Janeiro',
          'Fevereiro',
          'Março',
          'Abril',
          'Maio',
          'Junho',
          'Julho',
          'Agosto',
          'Setembro',
          'Outubro',
          'Novembro',
          'Dezembro',
        ],
        monthNamesShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
        chooseYear: 'Escolher ano',
        chooseMonth: 'Escolher mês',
        chooseDate: 'Escolher data',
        prevDecade: 'Década anterior',
        nextDecade: 'Próxima década',
        prevYear: 'Ano anterior',
        nextYear: 'Próximo ano',
        prevMonth: 'Mês anterior',
        nextMonth: 'Próximo mês',
        prevHour: 'Hora anterior',
        nextHour: 'Próxima hora',
        prevMinute: 'Minuto anterior',
        nextMinute: 'Próximo minuto',
        prevSecond: 'Segundo anterior',
        nextSecond: 'Próximo segundo',
        am: 'am',
        pm: 'pm',
        today: 'Hoje',
        weekHeader: 'Sem',
        firstDayOfWeek: 0,
        showMonthAfterYear: false,
        dateFormat: 'dd/mm/yy',
        weak: 'Fraca',
        medium: 'Média',
        strong: 'Forte',
        passwordPrompt: 'Digite uma senha',
        emptyFilterMessage: 'Nenhum resultado encontrado',
        searchMessage: '{0} resultados disponíveis',
        selectionMessage: '{0} itens selecionados',
        emptySelectionMessage: 'Nenhum item selecionado',
        emptySearchMessage: 'Nenhum resultado encontrado',
        fileChosenMessage: '{0} arquivos',
        noFileChosenMessage: 'Nenhum arquivo selecionado',
        emptyMessage: 'Nenhuma opção disponível',
        aria: {
          trueLabel: 'Verdadeiro',
          falseLabel: 'Falso',
          nullLabel: 'Não selecionado',
          star: '1 estrela',
          stars: '{star} estrelas',
          selectAll: 'Todos os itens selecionados',
          unselectAll: 'Todos os itens desmarcados',
          close: 'Fechar',
          previous: 'Anterior',
          next: 'Próximo',
          navigation: 'Navegação',
          scrollTop: 'Rolar para o topo',
          moveTop: 'Mover para o topo',
          moveUp: 'Mover para cima',
          moveDown: 'Mover para baixo',
          moveBottom: 'Mover para o final',
          moveToTarget: 'Mover para o destino',
          moveToSource: 'Mover para a origem',
          moveAllToTarget: 'Mover tudo para o destino',
          moveAllToSource: 'Mover tudo para a origem',
          pageLabel: 'Página {page}',
          firstPageLabel: 'Primeira página',
          lastPageLabel: 'Última página',
          nextPageLabel: 'Próxima página',
          prevPageLabel: 'Página anterior',
          rowsPerPageLabel: 'Linhas por página',
          jumpToPageDropdownLabel: 'Ir para a página',
          jumpToPageInputLabel: 'Digite a página',
          selectRow: 'Linha selecionada',
          unselectRow: 'Linha desmarcada',
          expandRow: 'Linha expandida',
          collapseRow: 'Linha recolhida',
          showFilterMenu: 'Mostrar menu de filtro',
          hideFilterMenu: 'Ocultar menu de filtro',
          filterOperator: 'Operador de filtro',
          filterConstraint: 'Restrição de filtro',
          editRow: 'Editar linha',
          saveEdit: 'Salvar edição',
          cancelEdit: 'Cancelar edição',
          listView: 'Visualização em lista',
          gridView: 'Visualização em grade',
          slide: 'Slide',
          slideNumber: '{slideNumber}',
        },
      },
    },
  },

  tailwindcss: {
    cssPath: '~/assets/css/main.css',
    configPath: 'tailwind.config.ts',
  },

  typescript: {
    strict: true,
    typeCheck: false,
  },

  runtimeConfig: {
    databaseUrl: process.env.DATABASE_URL,
    directUrl: process.env.DIRECT_URL,
    supabaseServiceRoleKey: process.env.SUPABASE_SERVICE_ROLE_KEY,
    supabaseJwtSecret: process.env.SUPABASE_JWT_SECRET,
    public: {
      supabaseUrl: process.env.SUPABASE_URL,
      supabaseAnonKey: process.env.SUPABASE_ANON_KEY,
    },
  },

  nitro: {
    moduleSideEffects: ['@prisma/client'],
    externals: {
      external: ['@prisma/client', '.prisma/client', 'prisma'],
    },
    compressPublicAssets: true,
    // Projeto Supabase roda em sa-east-1 (São Paulo) — sem isso, a função
    // serverless da Vercel sobe na região default (iad1, Virgínia) e toda
    // query paga round-trip intercontinental. gru1 é a região da Vercel em
    // São Paulo. Exige plano Vercel Pro (Hobby não permite escolher região).
    vercel: {
      regions: ['gru1'],
    },
  },

  routeRules: {
    '/login': { ssr: true },
    '/api/health': { headers: { 'cache-control': 'no-store' } },
    '/api/**': { headers: { 'cache-control': 'private, no-store' } },
  },

  build: {
    analyze: process.env.ANALYZE === 'true',
  },

  app: {
    head: {
      title: 'CPEK',
      htmlAttrs: { lang: 'pt-BR' },
      meta: [{ name: 'viewport', content: 'width=device-width, initial-scale=1' }],
      link: [
        { rel: 'preconnect', href: 'https://fonts.googleapis.com' },
        { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' },
        { rel: 'icon', type: 'image/svg+xml', href: '/favicon-light.svg', media: '(prefers-color-scheme: light)' },
        { rel: 'icon', type: 'image/svg+xml', href: '/favicon-dark.svg', media: '(prefers-color-scheme: dark)' },
        { rel: 'icon', type: 'image/svg+xml', href: '/favicon-light.svg' },
      ],
    },
  },
})
